project:
  type: website

website:
  title: "R Adventures"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Posts"
        href: posts/index.qmd
      - text: "About"
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/danG02
format:
  html:
    theme: cosmo
    css: styles.css
